# Generated by Django 3.2.5 on 2021-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_displacement', models.IntegerField(default=2000)),
                ('horsepower', models.IntegerField(default=200)),
                ('mileage', models.IntegerField(default=30000)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes')], max_length=30)),
                ('model', models.CharField(choices=[('A3', 'A3'), ('3 SERIES', '3 SERIES'), ('CLA', 'CLA')], max_length=30)),
                ('year', models.IntegerField(default=2015)),
            ],
        ),
    ]
